export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const OBTENER_PERFIL_USUARIO = "OBTENER_PERFIL_USUARIO";
export const CREAR_USUARIO = "CREAR_USUARIO";
export const ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO";
export const BORRAR_USUARIO = "BORRAR_USUARIO";

export const OBTENER_CARROS = "OBTENER_CARROS";
export const OBTENER_PERFIL_CARRO = "OBTENER_PERFIL_CARRO";
export const CREAR_CARRO = "CREAR_CARRO";
export const ACTUALIZAR_CARRO = "ACTUALIZAR_CARRO";
export const BORRAR_CARRO = "BORRAR_CARRO";
